### ISSUE TITLE
Allow empty entities in flows

### ISSUE THREAD

**Issue by uablrek** [Nordix/Meridio#143]
For now _all_ entries in flows _must_ be specified, e.g;
```yaml
    items:
    - name: flow1
      vips:
        - vip1
        - vip2
      source-subnets:
        - 0.0.0.0/0
        - 0:0:0:0:0:0:0:0/0
      source-port-ranges:
        - 1024-65535
      destination-port-ranges:
        - 5000-5003
      protocols:
        - tcp
      stream: stream1
```
The `source-subnets` and `source-port-ranges` are most likely rarely used (if ever) so it should be allowed to leave them empty, e.g;
```yaml
    items:
    - name: flow1
      vips:
        - vip1
        - vip2
      destination-port-ranges:
        - 5000-5003
      protocols:
        - tcp
      stream: stream1
```
The `nft` rules look like this (always);
```
meta l4proto @flow1-stream1-protocol ip saddr @flow1-stream1-src-ipv4 ip daddr @flow1-stream1-dst-ipv4 th dport @flow1-stream1-dst-port th sport @flow1-stream1-src-port counter packets 0 bytes 0 queue num 1
```
while they should look like;
```
meta l4proto @flow1-stream1-protocol ip daddr @flow1-stream1-dst-ipv4 th dport @flow1-stream1-dst-port counter packets 0 bytes 0 queue num 1
```
when src items are empty.

I assume the current implementation is out of convenience and usually that is fine but beside looking silly this also have a performance impact, _every single packet_ is unnecessary matched with sets that _always match_.

The situation is similar when `nfqlb` flows are used.

I would also like to allow "all-ip" flows like;
```yaml
    items:
    - name: flow1
      vips:
        - vip1
        - vip2
      stream: stream1
```
This would catch all non tcp-udp-sctp protocols that applications might need in the (near?) future.
