### ISSUE TITLE
Minimize the privileges needed for running Meridio

### ISSUE THREAD

**Issue by johlj** [Nordix/Meridio#15]
In order to minimize the requirements for running Meridio and strengthen security, evaluate and minimize the need for elevated privileges in Meridio

**Comment by LionelJouin** [comment]
- [x] Replace `privileged: true` with specific capabilities
- [ ] Run as non root

```
securityContext:
  runAsNonRoot: true
  capabilities:
    add: ["NET_ADMIN"]
```
returns:
`Error: container has runAsNonRoot and image will run as root`
