### ISSUE TITLE
Move destination port NAT to conduit

### ISSUE THREAD

**Issue by LionelJouin** [Nordix/Meridio#252]
**Is your feature request related to a problem? Please describe.**

The problem with the current implementation (using nftables with Flow) is that the source-port, source-subnet and the priority of the flow is not considered. So, if there is any overlap with any of the other flows, there will be "glitches" (traffic that should not be NATted will be NATted due to another flow).

**Describe the solution you'd like**

The NAT feature should be moved to the conduit level. A new property should be added to the conduit to support the Destination port NATing:
```
apiVersion: meridio.nordix.org/v1alpha1
kind: Conduit
metadata:
  name: conduit-a
  namespace: red
  labels:
    trench: trench-a
spec:
  type: stateless-lb
  destination-port-nats:
  - port: 80
    targetPort: 8080
    vips: 
    - vip-a
    protocol: UDP
  - port: 90
    targetPort: 9999
    vips: 
    - vip-a
    - vip-b
    protocol: TCP
  - port: 90
    targetPort: 5000
    vips: 
    - vip-a
    - vip-b
    protocol: UDP
```
All traffic going through the conduit with the properties defined in the conduit will be NATted.
- `port`: port the exposed by the service (in any of the conduit` flow).
- `targetPort`: port used by the target pod.
- `vips`: port will be NATted only if the traffic has one of the corresponding VIP address as destination address. 
- `protocol`: port will be NATted only if the traffic has to corresponding protocol. 

`port` will be NATted to `targetPort` for the ingress traffic and `targetPort` will be NATted to `port` for the outgoing traffic.

**Describe alternatives you've considered**

To avoid having glitches while NATting the destination port of the traffic, the NAT could be implemented as part of NFQLB, so NFQLB could consider every flow properties (byte-match, source IP/Port, priority...).
With the NAT implemented in NFQLB, it will mean the traffic should go through NFQLB on the way back to be "Un-NATted".

**Additional context**

https://github.com/Nordix/Meridio/pull/187
https://github.com/Nordix/Meridio-Operator/pull/99

**Comment by LionelJouin** [comment]
### 1

Only 1 protocol per entry (so <port>-<target-port>-<protocol> can be used as nft chain name)
```
apiVersion: meridio.nordix.org/v1alpha1
kind: Conduit
metadata:
  name: conduit-a
  namespace: red
  labels:
    trench: trench-a
spec:
  type: stateless-lb
  destination-port-nats:
  - port: 80
    targetPort: 8080
    vips: 
    - vip-a
    protocol: UDP
  - port: 80
    targetPort: 8080
    vips: 
    - vip-a
    protocol: TCP
  - port: 90
    targetPort: 9999
    vips: 
    - vip-a
    - vip-b
    protocol: TCP
  - port: 90
    targetPort: 5000
    vips: 
    - vip-a
    - vip-b
    protocol: UDP
```

### 2
multi-protocols per entry (nft chain name TDB)
```
apiVersion: meridio.nordix.org/v1alpha1
kind: Conduit
metadata:
  name: conduit-a
  namespace: red
  labels:
    trench: trench-a
spec:
  type: stateless-lb
  destination-port-nats:
  - port: 80
    targetPort: 8080
    vips: 
    - vip-a
    protocols:
    - TCP
    - UDP
  - port: 90
    targetPort: 9999
    vips: 
    - vip-a
    - vip-b
    protocols: 
    - TCP
  - port: 90
    targetPort: 5000
    vips: 
    - vip-a
    - vip-b
    protocol: 
    - UDP
```

### 3
Only 1 protocol and 1 VIP per entry (so <port>-<target-port>-<protocol>-<vip> can be used as nft chain name)
```
apiVersion: meridio.nordix.org/v1alpha1
kind: Conduit
metadata:
  name: conduit-a
  namespace: red
  labels:
    trench: trench-a
spec:
  type: stateless-lb
  destination-port-nats:
  - port: 80
    targetPort: 8080
    vip: vip-a
    protocol: UDP
  - port: 90
    targetPort: 9999
    vips: vip-a
    protocol: TCP
  - port: 90
    targetPort: 9999
    vip: vip-b
    protocol: TCP
  - port: 90
    targetPort: 5000
    vip: vip-a
    protocol: UDP
  - port: 90
    targetPort: 5000
    vip: vip-b
    protocol: UDP
```
