### ISSUE TITLE
Multus support

### ISSUE THREAD

**Issue by zolug** [Nordix/Meridio#326]
**Is your feature request related to a problem? Please describe.**
Currently setting up external interfaces is achieved by using NSM (via Remote VLAN NSE).
The intention is to provide an alternate Multus based configuration option to get hold of the external POD interface to be used by an FE.

**Describe the solution you'd like**
The idea is to extend the Attractor CRD so that its Interface block offers a second "Multus" Type. When enabled it should be possible to provide the name and namespace of the Network Attachment Definition (NAD) to be used. (There might be a need for setting the requested POD interface name as well.)

Also, since IP assignment should be also handled by an IPAM plugin (via NAD) when Multus is used, the ipv4/ipv6-prefix attributes in the Attractor shall be made optional depending on the Interface Type.

The proposed configuration would allow externalizing the FE network setup making the cluster agnostic to the underlying network fabric.

Example;
```
cat <<EOF | kubectl apply -f -
apiVersion: meridio.nordix.org/v1alpha1
kind: Attractor
metadata:
  name: attr-a1
  labels:
    trench: trench-a
  annotations:
    resource-template: "medium"
spec:
  replicas: 2
  gateways:
    - gateway-a1
    - gateway-a2
  composites:
    - load-balancer-a1
  vips:
    - vip-a1
    - vip-a2
    - vip-a3
  interface:
    name: eth0.100
    type: network-attachment
    network-attachment:
      - name: mynad
      - namespace: default
EOF

```

**Describe alternatives you've considered**
-

**Additional context**
-
